// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bellyful_proj_v._0._3.Models;

namespace bellyful_proj_v._0._3.Migrations
{
    [DbContext(typeof(bellyful_v03Context))]
    [Migration("20190908125648_AddNewColForVolunteer")]
    partial class AddNewColForVolunteer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("batch_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddAmount")
                        .HasColumnName("add_amount");

                    b.Property<int>("MealTypeId")
                        .HasColumnName("meal_type_id");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnName("production_date")
                        .HasColumnType("date");

                    b.HasKey("BatchId");

                    b.HasIndex("MealTypeId");

                    b.ToTable("batch");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("branch_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNumStreet")
                        .HasColumnName("address_num_street")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("TownCity")
                        .HasColumnName("town_city")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("BranchId");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.DietaryRequirement", b =>
                {
                    b.Property<int>("DietaryRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dietary_requirement_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasMaxLength(125)
                        .IsUnicode(false);

                    b.Property<string>("DietaryName")
                        .IsRequired()
                        .HasColumnName("dietary_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("MatchedSetMeal")
                        .HasColumnName("matched_set_meal")
                        .HasMaxLength(125)
                        .IsUnicode(false);

                    b.HasKey("DietaryRequirementId");

                    b.ToTable("dietary_requirement");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.MealInstock", b =>
                {
                    b.Property<int>("MealTypeId")
                        .HasColumnName("meal_type_id");

                    b.Property<int>("InstockAmount")
                        .HasColumnName("instock_amount");

                    b.HasKey("MealTypeId")
                        .HasName("PK__meal_ins__6F7616D8B7770892");

                    b.ToTable("meal_instock");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("meal_type_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MealTypeName")
                        .IsRequired()
                        .HasColumnName("meal_type_name")
                        .HasMaxLength(35)
                        .IsUnicode(false);

                    b.Property<string>("ShelfLocation")
                        .IsRequired()
                        .HasColumnName("shelf_location")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.HasKey("MealTypeId");

                    b.ToTable("meal_type");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("order_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AssignDatetime")
                        .HasColumnName("assign_datetime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnName("created_datetime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeliveredDatetime")
                        .HasColumnName("delivered_datetime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PickupDatetime")
                        .HasColumnName("pickup_datetime")
                        .HasColumnType("datetime");

                    b.Property<int>("RecipientId")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status_id")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("VolunteerId")
                        .HasColumnName("volunteer_id");

                    b.HasKey("OrderId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("StatusId")
                        .HasName("PK__order_st__3683B531D994162B");

                    b.ToTable("order_status");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("recipient_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnName("additional_info")
                        .HasMaxLength(2555)
                        .IsUnicode(false);

                    b.Property<string>("AddressNumStreet")
                        .IsRequired()
                        .HasColumnName("address_num_street")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("AdultsNum")
                        .HasColumnName("adults_num");

                    b.Property<int>("BranchId")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("DietaryRequirementId")
                        .HasColumnName("dietary_requirement_id");

                    b.Property<bool?>("DogOnProperty")
                        .HasColumnName("dog_on_property");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("OtherAllergyInfo")
                        .HasColumnName("other_allergy_info")
                        .HasMaxLength(2555)
                        .IsUnicode(false);

                    b.Property<string>("OtherReferralInfo")
                        .HasColumnName("other_referral_info")
                        .HasMaxLength(2555)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("Postcode")
                        .HasColumnName("postcode");

                    b.Property<int>("ReferralReasonId")
                        .HasColumnName("referral_reason_id");

                    b.Property<int?>("ReferrerId")
                        .HasColumnName("referrer_id");

                    b.Property<string>("TownCity")
                        .IsRequired()
                        .HasColumnName("town_city")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int>("Under5ChildrenNum")
                        .HasColumnName("under5_children_num");

                    b.Property<int>("_1117ChildrenNum")
                        .HasColumnName("11-17_children_num");

                    b.Property<int>("_510ChildrenNum")
                        .HasColumnName("5-10_children_num");

                    b.HasKey("RecipientId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DietaryRequirementId");

                    b.HasIndex("ReferralReasonId");

                    b.HasIndex("ReferrerId");

                    b.HasIndex("FirstName", "LastName", "AddressNumStreet")
                        .IsUnique()
                        .HasName("UQ__recipien__0D43C48A1E7C9BA3");

                    b.ToTable("recipient");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.ReferralReason", b =>
                {
                    b.Property<int>("ReferralReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("referral_reason_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("ReferralReasonId");

                    b.ToTable("referral_reason");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Referrer", b =>
                {
                    b.Property<int>("ReferrerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("referrer_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("OrganisationName")
                        .HasColumnName("organisation_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int>("RoleId")
                        .HasColumnName("role_id");

                    b.Property<string>("TownCity")
                        .HasColumnName("town_city")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("ReferrerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("FirstName", "LastName", "OrganisationName")
                        .IsUnique()
                        .HasName("UQ__referrer__21BE543F9515083C")
                        .HasFilter("[organisation_name] IS NOT NULL");

                    b.ToTable("referrer");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.ReferrerRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("role_name")
                        .HasMaxLength(35)
                        .IsUnicode(false);

                    b.HasKey("RoleId")
                        .HasName("PK__referrer__760965CC526A5A07");

                    b.ToTable("referrer_role");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Volunteer", b =>
                {
                    b.Property<int>("VolunteerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("volunteer_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("AlternativePhone")
                        .HasColumnName("alternative_phone")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int?>("BranchId")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<bool?>("IsAssignedUserAccount");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("PostCode")
                        .HasColumnName("post_code")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("PreferredPhone")
                        .IsRequired()
                        .HasColumnName("preferred_phone")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int?>("RoleId")
                        .HasColumnName("role_id");

                    b.Property<int?>("StatusId")
                        .HasColumnName("status_id");

                    b.Property<string>("TownCity")
                        .IsRequired()
                        .HasColumnName("town_city")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("VolunteerId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("FirstName", "LastName", "Dob")
                        .IsUnique()
                        .HasName("UQ__voluntee__5846F7A1E1DF965B");

                    b.ToTable("volunteer");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerEmergencyContact", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnName("volunteer_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnName("relationship")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("VolunteerId")
                        .HasName("PK__voluntee__0FE766B1B7894FD0");

                    b.ToTable("volunteer_emergency_contact");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerPoliceInfo", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnName("volunteer_id");

                    b.Property<DateTime>("PoliceVetDate")
                        .HasColumnName("police_vet_date")
                        .HasColumnType("date");

                    b.Property<bool>("PoliceVetVerified")
                        .HasColumnName("police_vet_verified");

                    b.HasKey("VolunteerId")
                        .HasName("PK__voluntee__0FE766B1C228BCB1");

                    b.ToTable("volunteer_police_info");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("role_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("role_name")
                        .HasMaxLength(35)
                        .IsUnicode(false);

                    b.HasKey("RoleId")
                        .HasName("PK__voluntee__760965CCABE2EDB2");

                    b.ToTable("volunteer_role");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("StatusId")
                        .HasName("PK__voluntee__3683B531D609B864");

                    b.ToTable("volunteer_status");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerTrainingInfo", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnName("volunteer_id");

                    b.Property<bool>("DeliveryTraining")
                        .HasColumnName("delivery_training");

                    b.Property<bool>("FirstAidRaining")
                        .HasColumnName("first_aid_raining");

                    b.Property<bool>("HSTraining")
                        .HasColumnName("H&S_training");

                    b.Property<string>("OtherTrainingSkill")
                        .HasColumnName("other_training_skill")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("VolunteerId")
                        .HasName("PK__voluntee__0FE766B1CF0C3AF3");

                    b.ToTable("volunteer_training_info");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Batch", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.MealType", "MealType")
                        .WithMany("Batch")
                        .HasForeignKey("MealTypeId")
                        .HasConstraintName("a batch has a meal type")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.MealInstock", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.MealType", "MealType")
                        .WithOne("MealInstock")
                        .HasForeignKey("bellyful_proj_v._0._3.Models.MealInstock", "MealTypeId")
                        .HasConstraintName("one meal type has one instock")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Order", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Recipient", "Recipient")
                        .WithMany("Order")
                        .HasForeignKey("RecipientId")
                        .HasConstraintName("an order has a recipient");

                    b.HasOne("bellyful_proj_v._0._3.Models.OrderStatus", "Status")
                        .WithMany("Order")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("every order has a status");

                    b.HasOne("bellyful_proj_v._0._3.Models.Volunteer", "Volunteer")
                        .WithMany("Order")
                        .HasForeignKey("VolunteerId")
                        .HasConstraintName("an order can assign a volunteer as delivery man");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Recipient", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Branch", "Branch")
                        .WithMany("Recipient")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("Recipient belones to a Branch");

                    b.HasOne("bellyful_proj_v._0._3.Models.DietaryRequirement", "DietaryRequirement")
                        .WithMany("Recipient")
                        .HasForeignKey("DietaryRequirementId")
                        .HasConstraintName("Recipient has a requirement");

                    b.HasOne("bellyful_proj_v._0._3.Models.ReferralReason", "ReferralReason")
                        .WithMany("Recipient")
                        .HasForeignKey("ReferralReasonId")
                        .HasConstraintName("Recipient has a Reason");

                    b.HasOne("bellyful_proj_v._0._3.Models.Referrer", "Referrer")
                        .WithMany("Recipient")
                        .HasForeignKey("ReferrerId")
                        .HasConstraintName("Recipient has/not has a Referrer")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Referrer", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.ReferrerRole", "Role")
                        .WithMany("Referrer")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("Referrer has/not has a role");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.Volunteer", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Branch", "Branch")
                        .WithMany("Volunteer")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("a volunteer belones to a branch");

                    b.HasOne("bellyful_proj_v._0._3.Models.VolunteerRole", "Role")
                        .WithMany("Volunteer")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("a volunteer has a role");

                    b.HasOne("bellyful_proj_v._0._3.Models.VolunteerStatus", "Status")
                        .WithMany("Volunteer")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("a volunteer has a status");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerEmergencyContact", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Volunteer", "Volunteer")
                        .WithOne("VolunteerEmergencyContact")
                        .HasForeignKey("bellyful_proj_v._0._3.Models.VolunteerEmergencyContact", "VolunteerId")
                        .HasConstraintName("a volunteer has a emergency contact");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerPoliceInfo", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Volunteer", "Volunteer")
                        .WithOne("VolunteerPoliceInfo")
                        .HasForeignKey("bellyful_proj_v._0._3.Models.VolunteerPoliceInfo", "VolunteerId")
                        .HasConstraintName("a volunteer has a police info");
                });

            modelBuilder.Entity("bellyful_proj_v._0._3.Models.VolunteerTrainingInfo", b =>
                {
                    b.HasOne("bellyful_proj_v._0._3.Models.Volunteer", "Volunteer")
                        .WithOne("VolunteerTrainingInfo")
                        .HasForeignKey("bellyful_proj_v._0._3.Models.VolunteerTrainingInfo", "VolunteerId")
                        .HasConstraintName("a voluteer has a train info");
                });
#pragma warning restore 612, 618
        }
    }
}
